### ISSUE TITLE
Error install 

### ISSUE THREAD

**Issue by apiasak** [425degree-developers/thaiaddress#4]
Cannot install krub.

```py
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Apipoj.Pi\Miniconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Apipoj.Pi\\AppData\\Local\\Temp\\pip-install-58s79h94\\thaiaddress\\setup.py'"'"'; __file__='"'"'C:\\Users\\Apipoj.Pi\\AppData\\Local\\Temp\\pip-install-58s79h94\\thaiaddress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Apipoj.Pi\AppData\Local\Temp\pip-install-58s79h94\thaiaddress\pip-egg-info'
         cwd: C:\Users\Apipoj.Pi\AppData\Local\Temp\pip-install-58s79h94\thaiaddress\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Apipoj.Pi\AppData\Local\Temp\pip-install-58s79h94\thaiaddress\setup.py", line 24, in <module>
        long_description=open("README.md").read(),
      File "C:\Users\Apipoj.Pi\Miniconda3\lib\encodings\cp874.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x84 in position 69: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by titipata** [comment]
@apiasak, it might be an error from `README.md` in `long_description=open("README.md").read()` since we include image into `README.md` also. Let me do a quick fix then you can try to re-install.
